src/components/input_field.tsx

This was causing issues in firefox

Remove unneeded event

---

src/components/image_upload.tsx
src/components/input_field_input.tsx
src/sass/_icons.sass
src/sass/_image_upload.sass
src/stories/form.stories.tsx

- set icon svg to 100% width 100% height
- add a placeholder label inside the image upload component

improve image upload component

---

src/stylesheets/_panel_arrow.scss
src/stylesheets/_toggle_button.scss

Fixes for the panel arrow sizing and the toggle button shadow

Minor fixes

---

src/components/input_fields/text_field.tsx

I think by using an input wrapper as a normal react component we can reach the same advantages as in the other PR  but with a simpler setup.
btw this link Alan told me about is interesting: https://reactjs.org/docs/composition-vs-inheritance.html

Experience with using wrapper as component

---

src/components/input_fields/__tests__/textarea_field.test.tsx
src/components/input_fields/textarea_field.tsx
src/stylesheets/_base.scss
src/stylesheets/_forms.scss
src/utils/split_text_by_new_line.tsx

as requested in https://docs.google.com/presentation/d/1RAURl-eRmsAZUxA1bNGf2kNidV5BvfNdVs5s5m2OeO4/edit?ts=5bb7216f#slide=id.g43d723e7e9_1_80

Adding min/max width/height to textareas

---

src/components/__tests__/__snapshots__/button.test.tsx.snap
src/components/button.tsx

Internal links could not be disabled or could not have an ID.
This PR should fix that.

Passing props to internal link as well

---

src/components/__tests__/__snapshots__/setting_panel.test.tsx.snap
src/components/__tests__/setting_panel.test.tsx
src/components/setting_panel.tsx
src/stories/button.stories.tsx
src/stories/layout.stories.tsx
src/stylesheets/_setting_panel.scss
src/stylesheets/main.scss

This PR adds the setting panel component from cura connect

add settings panel component

---

src/components/__tests__/__snapshots__/popup.test.tsx.snap
src/components/__tests__/__snapshots__/popup_prompt.test.tsx.snap
src/components/__tests__/popup.test.tsx
src/components/modal.tsx
src/components/popup.tsx
src/components/popup_prompt.tsx
src/stories/modal.stories.tsx
src/stylesheets/_modal.scss
src/stylesheets/_popup.scss
src/stylesheets/_progress_bar.scss

The PR adds multi-step functionality and a size prop to the popup component

Add multi-step functionality to the popup component

---

src/components/__tests__/__snapshots__/user_account_menu.test.tsx.snap
src/components/context_menu_item.tsx
src/components/grid_item.tsx
src/components/user_account_menu.tsx

With this change we can make better use of IDs and classes to test our UIs.

Adding more support for IDs and classes

---

src/components/__tests__/popup.test.tsx
src/components/__tests__/popup_base.test.tsx
src/components/__tests__/popup_prompt.test.tsx
src/components/popup.tsx
src/components/popup_base.tsx
src/components/popup_prompt.tsx
src/stories/modal.stories.tsx

Issue: https://jira.ultimaker.com:8443/browse/STAR-318
Used in: https://github.com/Ultimaker/stardust-marketplace_portal/pull/144
This can be used to display errors in the popup.

STAR-318: Allowing a footer in the popup components

---

src/components/__tests__/__snapshots__/tooltip.test.tsx.snap
src/components/__tests__/tooltip.test.tsx
src/components/tooltip.tsx

change pointer events to regular mouse events

---

src/stylesheets/_header.scss
src/stylesheets/_slide_in_panel.scss
src/stylesheets/_variables.scss

The PR allows the scss variables to be overridden.

Improve overriding defaults

---

src/stylesheets/_popup.scss

CL-1013-popup-style-moved-from-print-cluster

---

src/components/__tests__/__snapshots__/carousel.test.tsx.snap
src/components/__tests__/__snapshots__/navigation.test.tsx.snap
src/components/__tests__/__snapshots__/page.test.tsx.snap
src/components/__tests__/__snapshots__/page_section.test.tsx.snap
src/components/__tests__/__snapshots__/ratings.test.tsx.snap
src/components/__tests__/page_section.test.tsx
src/components/carousel.tsx
src/components/header.tsx
src/components/navigation.tsx
src/components/page.tsx
src/components/page_section.tsx
src/components/ratings.tsx
src/stylesheets/_layout.scss
src/stylesheets/_page.scss
src/stylesheets/_ratings.scss

Improvements to Page and Ratings components.
It also adds a new PageSection component.

STAR-326 improvements to Page and Ratings components

---

src/components/__tests__/__snapshots__/header.test.tsx.snap
src/components/__tests__/__snapshots__/navigation.test.tsx.snap
src/components/__tests__/__snapshots__/user_account_menu.test.tsx.snap
src/components/__tests__/navigation.test.tsx
src/components/header.tsx
src/components/icons/cura_logo.tsx
src/components/icons/ultimaker_logo.tsx
src/components/navigation.tsx
src/components/user_account_menu.tsx
src/stories/layout.stories.tsx
src/stylesheets/_header.scss
src/stylesheets/_navigation.scss
src/stylesheets/_user_account_menu.scss

This PR adds a sign out button and account menu button to the mobile navigation menu, plus some other small improvements. It also adds a header story to storybook.

STAR-333 improve header bar

---

src/components/navigation.tsx

Navigation component should not be responsible for whether it is visible. This PR changes this.

Navigation component changes

---

package.json

Add namespace to package name

---

src/components/__tests__/response_error.test.tsx
src/components/response_error.tsx
src/stories/error_message.stories.tsx
src/utils/__tests__/i18n.test.tsx
src/utils/i18n.tsx

* Change how translation file are loaded (to increase performance, only the active locale file is loaded).
* Fixes in the I18n class.
We should add more tests for i18n, but let's do that in a separate PR.

Fix translation utility class

---

src/stories/layout.stories.tsx
src/stylesheets/_base.scss
src/stylesheets/_checkbox.scss
src/stylesheets/_header.scss
src/stylesheets/_navigation.scss
src/stylesheets/_table.scss

This PR makes some improvements to the table css and the checkbox css

STAR-480 my teams fixes/improvements

---

src/utils/i18n.tsx

CL-1302 Use the correct `get-text` function for plurals

---

src/components/__tests__/__snapshots__/header.test.tsx.snap
src/components/__tests__/__snapshots__/header_old.test.tsx.snap
src/components/__tests__/__snapshots__/navigation.test.tsx.snap
src/components/__tests__/__snapshots__/navigation_old.test.tsx.snap
src/components/__tests__/__snapshots__/setting_panel.test.tsx.snap
src/components/__tests__/__snapshots__/slide_out_container.test.tsx.snap
src/components/__tests__/header.test.tsx
src/components/__tests__/header_old.test.tsx
src/components/__tests__/navigation.test.tsx
src/components/__tests__/navigation_old.test.tsx
src/components/header.tsx
src/components/header_old.tsx
src/components/navigation.tsx
src/components/navigation_old.tsx
src/components/slide_out_container.tsx
src/stories/layout.stories.tsx
src/stylesheets/_header.scss
src/stylesheets/_header_old.scss
src/stylesheets/_navigation.scss
src/stylesheets/_navigation_old.scss
src/stylesheets/_slide_out_container.scss
src/stylesheets/_variables.scss
src/stylesheets/main.scss

This PR adds a new version of the header and navigation components, and renames the old ones.

STAR-519 new header

---

src/components/__tests__/image_upload.test.tsx
src/components/image_upload.tsx

this is probably the way it should be fixed, see other PR for a fix which does not break the testing logic.
See other PR: https://github.com/Ultimaker/react-web-components/pull/194
Which solution is the best?

Fix showing image cropper

---

src/components/input_fields/__tests__/__snapshots__/date_field.test.tsx.snap
src/components/input_fields/__tests__/date_field.test.tsx
src/components/input_fields/date_field.tsx

The PR changes the date field to receive and return an ISO date

STAR-593 Fix date picker

---

package.json
yarn.lock

updated:
- jest
- webpack
- node-sass

Fix install errors

---

package.json
src/components/__tests__/__snapshots__/context_menu.test.tsx.snap
src/components/__tests__/context_menu.test.tsx
src/components/context_menu.tsx
src/stories/menu.stories.tsx
src/stylesheets/_context_menu.scss
src/stylesheets/_variables.scss
yarn.lock

STAR-577
Add a disabled option to the context menu component.

STAR-577 add disabled option to the context menu

---

src/index.tsx
src/stories/utils.stories.tsx
src/utils/__tests__/array_intersection.test.tsx
src/utils/array_intersection.tsx

Extracted this util function from the print-cluster, and improved it a little.

Add array intersect util

---

src/index.tsx

Expose IconProps for use in stardust-web-components

---

package.json
src/components/icons/info_circular_icon.tsx
src/index.tsx
src/stories/icons.stories.tsx
src/stylesheets/_icons.scss

CS-220 add new icon

---

src/components/header.tsx

Clean up headerLogo which is no longer used in the Header component.
@ianpaschal Could you let me know if it involves further clean up/update for other applications/tests? Thank you!

Remove headerLogo from the Header component

---

package.json

v5.6.8 is available at npm: https://www.npmjs.com/package/@ultimaker/react-web-components/v/5.6.8

Upgrade to 5.6.8 for <ImageUpload /> placeholder changes

---

package-lock.json
package.json

Release 5.6.11

---

package.json

Remove unneeded prop-types

---

.storybook/webpack.config.js
package-lock.json
package.json
src/components/search_bar/__tests__/__snapshots__/search_bar.test.tsx.snap
src/components/search_bar/__tests__/search_bar.test.tsx
src/components/search_bar/search_bar.tsx
src/index.ts
src/stylesheets/_accessibility.scss
src/stylesheets/_input-text.scss
src/stylesheets/_search_bar.scss

Add a (hidden) label for the new SearchBar component.

Improve new search bar accessibility

---

package-lock.json
package.json

Includes: Resource view more button and new "eye" icons

Release 5.8.0

---

package-lock.json
package.json
src/components/response_error.tsx

This just removes the pop up from the error message component.

CS-215 Remove the pop up from the error message component

---

README.md

Add Actions and Dependabot badges

---

src/stories/colors.stories.tsx
src/stylesheets/_buttons.scss
src/stylesheets/_carousel.scss
src/stylesheets/_checkbox.scss
src/stylesheets/_colors.scss
src/stylesheets/_drop_down_menu.scss
src/stylesheets/_icons.scss
src/stylesheets/_input-text.scss
src/stylesheets/_input_fields.scss
src/stylesheets/_navigation.scss
src/stylesheets/_panel_arrow.scss
src/stylesheets/_pill.scss
src/stylesheets/_progress_bar.scss
src/stylesheets/_spinner.scss
src/stylesheets/_sub_navigation_menu.scss
src/stylesheets/_toggle_button.scss
src/stylesheets/_tooltip.scss
src/stylesheets/_variables.scss

There were no weird stuff in the storybook after the change.

CS-781 Implement new UM blue

---

package-lock.json
package.json
src/components/input_fields/__tests__/__snapshots__/checkbox_field.test.tsx.snap
src/components/input_fields/__tests__/__snapshots__/children_field.test.tsx.snap
src/components/input_fields/__tests__/__snapshots__/code_field.test.tsx.snap
src/components/input_fields/__tests__/__snapshots__/date_field.test.tsx.snap
src/components/input_fields/__tests__/__snapshots__/default_input_field.test.tsx.snap
src/components/input_fields/__tests__/__snapshots__/file_upload_field.test.tsx.snap
src/components/input_fields/__tests__/__snapshots__/image_upload_field.test.tsx.snap
src/components/input_fields/__tests__/__snapshots__/select_field.test.tsx.snap
src/components/input_fields/__tests__/__snapshots__/static_field.test.tsx.snap
src/components/input_fields/__tests__/__snapshots__/tags_field.test.tsx.snap
src/components/input_fields/__tests__/__snapshots__/textarea_field.test.tsx.snap
src/components/input_fields/__tests__/code_field.test.tsx
src/components/input_fields/__tests__/default_input_field.test.tsx
src/components/input_fields/input_field_wrapper.tsx

Default should be to show validation errors.
Co-Authored-By: Xiaozhou Li <x.li@ultimaker.com>

Add showValidationError default prop

---

src/stylesheets/_drop_down_menu_base.scss

CS-860 Keep context menus inside the main area under the header

---

package-lock.json
package.json
src/stylesheets/_drop_down_menu_base.scss

the version update commit didn't go through.

CS-860 context menu fix with selector
