Ultimaker/react-web-components

src/components/form.tsx
- This is necessary for the oAuth2 login page, for example (forgot your password link).
- Passing DOM elements as child gave the error: "React does not recognize the `validationErrorMsg` prop on a DOM element"
=> Allowing non-inputs in the form

src/stylesheets/_context_menu.scss
The convert script made a couple of errors in `_context_menu.scss`. These look to be the only cases.
=> Fix context menu classes after converting to scss

src/components/__tests__/__snapshots__/file_upload.test.tsx.snap, src/components/file_upload.tsx, src/components/input_fields/file_upload_field.tsx, src/stories/form.stories.tsx, src/stylesheets/_forms.scss
This PR makes the 'accept' prop available for the file input field.
Also it changes the styling: With opacity=0 and position=absolute the file input field should not be displayed, but is still be available by using the tab character and clicking on the labels.
=> Adding 'accept' to FileUpload, giving opacity=0 instead of display=none

src/components/__tests__/__snapshots__/select_list.test.tsx.snap, src/components/__tests__/select_list.test.tsx, src/components/select_list.tsx, src/components/select_list_item.tsx, src/stylesheets/_context_menu.scss
This PR adds accessibility to the select list component. It should now be possible to use the component with only the keyboard. This means you can now tab to it, then use the up and down arrows to focus an option, and enter to select an option.
=> Make select list accessible

src/components/user_account_menu.tsx, src/stories/menu.stories.tsx
This allows the manage account button in the account dropdown to be optional. I want to use this in the account.ultimaker.com page where you're already on the management portal and just want to show the profile picture and sign out button in the top right.
=> Hide account management URL button if no URL is passed

src/components/input_fields/__tests__/__snapshots__/static_field.test.tsx.snap, src/components/input_fields/__tests__/static_field.test.tsx, src/components/input_fields/static_field.tsx, src/components/input_fields/tags_field.tsx, src/stories/form.stories.tsx
This PR adds a new input type that simply outputs its value and eventual children.
We can use this simplified version for fields that are always read-only anyway.
=> STAR-299: Static field

src/components/__tests__/__snapshots__/loading_page.test.tsx.snap, src/components/__tests__/loading_page.test.tsx, src/components/loading_page.tsx, src/stories/loading.stories.tsx
By default, this PR will change the loading page behavior so that it only gets rendered after 0,5 second.
This way we can avoid flashing the spinner in fast pages, and only show it when it takes long.
=> Adding a timeout to the loading page

src/stylesheets/_variables.scss
This is to fix a bug in safari when using linear-gradient with $color-transparent
=> change $color-transparent to a white base

src/components/__tests__/__snapshots__/context_menu_item.test.tsx.snap, src/components/__tests__/__snapshots__/drop_down_menu_base.test.tsx.snap, src/components/__tests__/drop_down_menu_item.test.tsx, src/components/context_menu_item.tsx, src/components/drop_down_menu_base.tsx, src/components/drop_down_menu_item.tsx, src/components/spinner.tsx, src/stylesheets/_drop_down_menu_base.scss
An onCloseMenuHandler was passed from DropDownMenuBase to DropDownMenuItem, but this is causing some issues in cura connect. To simplify things, closing the menu on item click will be removed. Closing the menu on click outside will still work.
CL-1207
=> remove onCloseMenuHandler from the drop down menu

src/components/__tests__/drop_down_menu_item.test.tsx, src/components/drop_down_menu.tsx, src/components/drop_down_menu_base.tsx, src/components/drop_down_menu_item.tsx, src/stories/menu.stories.tsx
Unlike the new version of the context menu, drop down menus (more specifically select menus) need to be uncontrolled. This PR adds closing the menu when a menu item is clicked.
=> close drop down menus on item click

src/components/image_cropper.tsx
To keep both parcel and webpack happy, lodash functions need to be imported this way for now.
=> Import the old way for now

.gitlab-ci.yml
Because the process is running as root inside the docker container.
=> Specify --unsafe-perm on publish

package.json, src/components/__tests__/__snapshots__/carousel.test.tsx.snap, src/stylesheets/main.scss, yarn.lock
Updates react-alice-carousel to 1.14.0 and using the new import location of that library. Was already done in some project using this library as we used 1.13.0 and higher as dependency. Component tested using the storybook UI.
=> Fix carousel dependency

src/components/__tests__/slide_in_panel.test.tsx, src/components/slide_in_panel.tsx, src/utils/__tests__/toggle_scrolling.tsx, src/utils/toggle_scrolling.tsx
I've added some utils to actually block mouse scroll input programatically.
Why didn't I do it in CSS?
Because I see doing it in CSS as a hack. What we truly want is to control when to ignore scroll input, namely based on component props. Using a `noscroll` sort of makes it look like that's what's happening, but of course leads to other bugs, such as the fact that the page height is overridden and then scroll bars disappear. Hence: hacky.
So after some research I found this to be the most stable solution which works for desktop and mobile and truly does what we actually want (as I see it).
=> CS-125 Fix shifting header items

.gitlab-ci.yml, .npmrc
This is a better solution because the inclusion of a `.npmrc` file meant adding or removing any packages with yarn threw an error and failed. It's true a dev could just delete that file but they'd have to make sure they never accidentally committed that change, and requiring the deletion of config to run `yarn install` is uncool.
=> Set auth token within .gitlab-ci.yml

src/components/__tests__/__snapshots__/box_placeholder.test.tsx.snap, src/components/__tests__/box_placeholder.test.tsx, src/components/box_placeholder.tsx, src/stylesheets/_box_placeholder.scss
* According to [this requirement](https://jira.ultimaker.com/browse/CS-256?focusedCommentId=90624&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-90624) and [this requirement](https://jira.ultimaker.com/browse/CS-256?focusedCommentId=90624&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-90624) the box placeholder can be grey or white (transparent); adding the functionality to enable it. Default: transparent.
=> Update `<BoxPlaceholder />`: allow choosing background colours

src/components/__tests__/image_upload.test.tsx, src/components/image_upload.tsx, src/components/input_fields/image_upload_field.tsx
This PR aims enabling the rendering of a placeholder for an image upload field.
The background of the upload field is grey. Hide `<UploadIcon />` (the "upload cloud") when there's a placeholder (the upload icon is only shown when the cursor is hover on the placeholder).
By default (when the developer haven't specify anything for `<ImageUploadField />`) it will be a `<div>` displaying a square or round box, depending on the `shape` parameter.
For person the shape is round, and for others (material, plug-in etc.) the shape is square.
See [CS-256](https://jira.ultimaker.com/browse/CS-256) for details.
Preview:
1. Default
2. Person
3. Other
=> Allow `<ImageUpload />` and `<ImageUploadField />` accept placeholderType

src/components/input_fields/__tests__/image_upload_field.test.tsx, src/components/input_fields/image_upload_field.tsx
Upon the QA of CS-256, [Meike discovered that](https://jira.ultimaker.com/browse/CS-256?focusedCommentId=91185&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-91185) the placeholder of the "release details" page cannot be displayed, if the user saves a draft without uploading an image.
The issue is because of the use of `staticField` in `<ImageUploadField />`. This PR adds a method for this component, allowing the rendering of a placeholder (`person` or `other`), if there's no imageURL specified.
Preview:
=> CS-256 fix: Display the placeholder for `staticField` when there's no user-uploaded image

package-lock.json, package.json
stardust-mycloud complained that webpack should be installed manually
because it was a peerDependency for css-loader.
stardust-mycloud uses parcel instead of webpack so this requirement
seems to make no sense.
'npm ls css-loader' showed that react-web-components was the culprit.
=> Move css-loader dependency

tsconfig.json
Remove unnecessary compiler options and clean up exclude patterns.
Slightly increase strictness.
Order `compilerOptions` alphabetically.
=> Clean up tsconfig.json

jest.config.js
Remove default values.
Remove unnecessary 'transformIgnorePatterns' property.
Explicitly set 'rootDir' property to './src'.
=> Clean up Jest config further

src/components/__tests__/drop_down_menu_base.test.tsx, src/components/drop_down_menu_base.tsx
This is to fix all dropdowns closing on other than chrome browsers, by pressing any key.
=> CS-466 fix unintended keys closing dropdowns

src/components/__tests__/__snapshots__/image_upload.test.tsx.snap, src/components/image_upload.tsx, src/components/input_fields/image_upload_field.tsx, src/stylesheets/_image_upload.scss
Issue: `<ImageUploadField />` has a property `maxMb`. Before this PR, when the size of the uploaded image exceeds `maxMb`, it gives no indication for the user what went wrong. Now we add a warning message.
See [CS-255](https://jira.ultimaker.com/browse/CS-255) for more details.
Here is the update for the common component, namely `<ImageUploadField />`.
The preview images below show how the change looks like in the Contributor Portal:
=> CS-255 Image file size exceeds warning message

src/components/__tests__/tags_selector.test.tsx, src/components/tags_selector.tsx
For now, this just doesn't add tags a 2nd time if they're duplicates. It's the super simple fix to the issue we're having. That being said, maybe we want a better user experience, so that requires some discussion.
=> CS-415 Minimum amount of code needed to prevent duplicates

src/components/__tests__/__snapshots__/pill.test.tsx.snap, src/components/pill.tsx, src/stylesheets/_pill.scss
This is a tiny example in which I've "refactored" the Pill component and introduced a few new patterns.
- Use BEM class selectors
- Avoid nesting in Sass
- Use consts for class selectors in the `.tsx` files and declare them at the top of the file
- Remove comments that only take up space but add nothing that is not already clear from the file itself
- Use `React.FC<Props>` instead of the deprecated `React.StatelessComponent<Props>`
=> Refactor Pill component

src/components/__tests__/__snapshots__/image_cropper.test.tsx.snap, src/components/image_cropper.tsx, src/components/image_upload.tsx, src/components/input_fields/image_upload_field.tsx
Now it is possible to zoom out the uploaded images :)
Furthermore, make it possible to adjust the min/max scales, as well as the scale step, via `<ImageUploadField />`.
See CS-28 for details.
Original size:
Scaled:
=> CS-28 Make cropper zoom out possible

package-lock.json, package.json, src/components/__tests__/image_cropper.test.tsx, src/components/image_cropper.tsx
After cropping, the avatar editor would upload the full-size image even
though these images are used at much smaller dimensions.
This change uses a version of the image scaled down to the size of the
canvas which results in considerable file size reduction for large images.
(I used a different format for commit messages, thoughts?)
=> CS-615: Use a scaled image instead of a full size image

package-lock.json, package.json, src/components/__tests__/__snapshots__/image_cropper.test.tsx.snap, src/components/__tests__/image_cropper.test.tsx, src/components/image_cropper.tsx
We use avatar images at 180x180 pixels on the profile page of
account.ultimaker.com but we only provide a 130x130px circle when cropping
images. By removing the 25px border that was previously used, we get the
full 180x180px of the cropper tool.
**before**
**after**
=> Remove the border from the ImageCropper

src/components/search_bar/__tests__/__snapshots__/search_bar.test.tsx.snap, src/components/search_bar/search_bar.tsx
A SearchBar is responsible for its own internal state and rendering once
it's mounted.
This change allows a parent component to force SearchBar to update its
internal state (the value of query) to a new value.
Geneate a uuid only once.
=> Improve SearchBar

src/stylesheets/_buttons.scss, src/stylesheets/_carousel.scss, src/stylesheets/_checkbox.scss, src/stylesheets/_icons.scss, src/stylesheets/_input_fields.scss, src/stylesheets/_variables.scss
Some of the colors used also touched the checkboxes and the Alice
Carousel component. These have been converted to $um-* colors as well.
This should pave the way for stardust-web buttons to be dropped in as
replacement for the old buttons.
=> Use new colors for buttons states

package-lock.json, package.json, src/components/search_bar/__tests__/search_bar.test.tsx, src/components/search_bar/search_bar.tsx
Switch to the [new way](https://github.com/uuidjs/uuid/blob/master/README.md#upgrading-from-uuid3) of importing and update the corresponding test.
Closes #355
=> Update uuid to v7.0.0
